# Generated by Django 4.2.10 on 2025-11-01 10:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255, null=True)),
                ('model_code', models.CharField(max_length=255)),
                ('qc_no', models.IntegerField()),
                ('part_no', models.IntegerField(null=True)),
                ('part_name', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('checkpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(max_length=255, null=True)),
                ('highlight', models.CharField(max_length=255, null=True)),
                ('attribute', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('concern', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_operation', models.CharField(max_length=255, null=True)),
                ('remark_image', models.CharField(max_length=255)),
                ('vehicle_platform', models.CharField(max_length=255)),
                ('emp_token', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('part_time', models.CharField(max_length=255, null=True)),
                ('image_path', models.CharField(max_length=255, null=True)),
                ('vin', models.CharField(max_length=255, null=True)),
                ('actual_text', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_text', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_processing_type', models.IntegerField(blank=True, null=True)),
                ('actual_text_new', models.CharField(blank=True, max_length=255, null=True)),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='attribute_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='battery_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_qr', models.CharField(max_length=255)),
                ('battery_qr', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='bodyshop_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=255)),
                ('vin_ocr_result', models.CharField(max_length=255)),
                ('vin_status', models.CharField(max_length=255)),
                ('vin_image', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='boundingbox_cd_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.IntegerField(null=True)),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('top', models.IntegerField()),
                ('bottom', models.IntegerField()),
                ('c1_r_from', models.IntegerField(default=0)),
                ('c1_g_from', models.IntegerField(default=0)),
                ('c1_b_from', models.IntegerField(default=0)),
                ('c1_r_to', models.IntegerField(default=0)),
                ('c1_g_to', models.IntegerField(default=0)),
                ('c1_b_to', models.IntegerField(default=0)),
                ('c2_r_from', models.IntegerField(default=0)),
                ('c2_g_from', models.IntegerField(default=0)),
                ('c2_b_from', models.IntegerField(default=0)),
                ('c2_r_to', models.IntegerField(default=0)),
                ('c2_g_to', models.IntegerField(default=0)),
                ('c2_b_to', models.IntegerField(default=0)),
                ('c1IgnorePixelCount', models.IntegerField(default=0)),
                ('c2IgnorePixelCount', models.IntegerField(default=0)),
                ('pixel_range', models.IntegerField(default=0)),
                ('greater_less_than', models.CharField(max_length=50)),
                ('ok_nok', models.CharField(max_length=10)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='boundingbox_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_value', models.IntegerField()),
                ('right_value', models.IntegerField()),
                ('top_value', models.IntegerField()),
                ('bottom_value', models.IntegerField()),
                ('box_type', models.CharField(max_length=255)),
                ('position', models.IntegerField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='characters_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alphabet', models.BooleanField()),
                ('is_number', models.BooleanField()),
                ('character_type', models.CharField(max_length=50)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='color_code_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=255)),
                ('color_name', models.CharField(max_length=255)),
                ('r_from', models.IntegerField(default=0)),
                ('g_from', models.IntegerField(default=0)),
                ('b_from', models.IntegerField(default=0)),
                ('r_to', models.IntegerField(default=0)),
                ('g_to', models.IntegerField(default=0)),
                ('b_to', models.IntegerField(default=0)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='concern_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='delete_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('data_id', models.IntegerField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='highlight_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_process', models.CharField(max_length=255)),
                ('no_of_char', models.IntegerField(null=True)),
                ('position_of_text', models.IntegerField()),
                ('variable', models.CharField(max_length=255)),
                ('description_of_text', models.CharField(max_length=255)),
                ('is_qr_applicable', models.IntegerField(default=1)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='location_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mst_com_cs_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('sync_status', models.BooleanField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mst_com_ser_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('retry_time', models.IntegerField(verbose_name=1000)),
                ('sync_status', models.BooleanField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mst_settableFields_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purging_limit', models.BigIntegerField()),
                ('rotation_degree', models.IntegerField()),
                ('capture_time', models.IntegerField()),
                ('buzzer_ok_time', models.BigIntegerField()),
                ('buzzer_nok_time', models.IntegerField()),
                ('result_refresh_time', models.IntegerField()),
                ('is_nok_image_capture_enable', models.BooleanField(null=True)),
                ('is_iot_hooter_auto', models.BooleanField(null=True)),
                ('is_body_shop_enable', models.BooleanField(null=True)),
                ('is_ok_concern_enable', models.BooleanField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='operation_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_operation', models.CharField(max_length=255, null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('model_code_length', models.IntegerField(blank=True, default=16, null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.TextField()),
                ('model', models.CharField(default='', max_length=255)),
                ('sync_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PurgingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purging_limit', models.IntegerField()),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='severity_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_name', models.CharField(max_length=255)),
                ('Shift_From', models.TimeField(max_length=8)),
                ('Shift_To', models.TimeField()),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_level_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('token', models.IntegerField(unique=True)),
                ('user_level', models.CharField(max_length=255, null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantFuelCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_character', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='variant_images/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_variant_images/')),
                ('processing_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(max_length=100)),
                ('model_code', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('show_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('no_of_units_displayed', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vin_report_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255)),
                ('model_code', models.CharField(max_length=255)),
                ('answer_status', models.CharField(max_length=255)),
                ('shift_name', models.CharField(max_length=255)),
                ('vehicle_platform', models.CharField(max_length=255)),
                ('emp_token', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('qc_no', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Show_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('Date_Field', models.DateField()),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_webapp.shift')),
            ],
        ),
        migrations.CreateModel(
            name='part_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.IntegerField()),
                ('part_name', models.CharField(max_length=255)),
                ('image_path', models.ImageField(blank=True, max_length=255, null=True, upload_to='image_path/image_path/part_images/')),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_operation', models.CharField(default=1, max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('image_processing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.image_processing')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.platform')),
            ],
        ),
        migrations.CreateModel(
            name='model_code_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=16)),
                ('model_description', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.platform')),
            ],
        ),
        migrations.CreateModel(
            name='model_checkpoint_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.TextField()),
                ('image_path', models.ImageField(blank=True, max_length=255, null=True, upload_to='image_path/image_path/part_images/')),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('image_processing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.image_processing')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.model_code_tbl')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.part_tbl')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='checkpoint_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(max_length=255)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.part_tbl')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.platform')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('data_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='part_tbl',
            constraint=models.UniqueConstraint(fields=('platform', 'part_name'), name='unique_part_name_per_platform'),
        ),
    ]
