# Generated by Django 5.0.14 on 2025-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_checkpoint_tbl',
            name='zoom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
