# Generated by Django 5.0.14 on 2025-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0002_model_checkpoint_tbl_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute_count_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
                ('total_count', models.IntegerField()),
                ('attribute_ok_count', models.IntegerField()),
                ('attribute_nok_count', models.IntegerField()),
                ('qc', models.IntegerField(null=True)),
                ('data_date', models.DateField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='higlight_count_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=255)),
                ('total_count', models.IntegerField()),
                ('highlight_ok_count', models.IntegerField()),
                ('highlight_nok_count', models.IntegerField()),
                ('qc', models.IntegerField(null=True)),
                ('data_date', models.DateField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='severity_count_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=255)),
                ('total_count', models.IntegerField()),
                ('severity_ok_count', models.IntegerField()),
                ('severity_nok_count', models.IntegerField()),
                ('qc', models.IntegerField(null=True)),
                ('data_date', models.DateField(null=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
