# Generated by Django 5.0.14 on 2025-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0003_attribute_count_tbl_higlight_count_tbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_checkpoint_tbl',
            name='zoom',
        ),
        migrations.AddField(
            model_name='image_processing',
            name='zoom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
