# Generated by Django 5.0.14 on 2025-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0004_remove_model_checkpoint_tbl_zoom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_checkpoint_tbl',
            name='zoom',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
