# Generated by Django 5.0.14 on 2025-11-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0005_model_checkpoint_tbl_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_checkpoint_tbl',
            name='zoom',
        ),
    ]
