# Generated by Django 5.0.14 on 2025-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0006_remove_model_checkpoint_tbl_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_processing',
            name='zoom',
            field=models.FloatField(null=True),
        ),
    ]
