# Generated by Django 5.0.14 on 2025-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0007_alter_image_processing_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_code_tbl',
            name='platform',
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='burden',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='ferrule_direction',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='label_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='no_of_cables',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='ratio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='model_code',
            field=models.CharField(max_length=255),
        ),
    ]
