# Generated by Django 5.0.14 on 2025-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0008_remove_model_code_tbl_platform_model_code_tbl_burden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_code_tbl',
            old_name='model_description',
            new_name='part',
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='no_of_ferrules',
            field=models.IntegerField(default=0),
        ),
    ]
