# Generated by Django 5.0.14 on 2025-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0009_rename_model_description_model_code_tbl_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_code_tbl',
            name='burden',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ferrule_direction',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Up', 'Up'), ('Down', 'Down')], max_length=50),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='no_of_ferrules',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ratio',
            field=models.CharField(choices=[('1:1', '1:1'), ('2:1', '2:1'), ('3:1', '3:1')], max_length=50),
        ),
    ]
