# Generated by Django 5.0.14 on 2025-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0010_alter_model_code_tbl_burden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ferrule_direction',
            field=models.CharField(choices=[('US1-US2, VS1-VS2, WS1-WS2', 'US1-US2, VS1-VS2, WS1-WS2'), ('WS1-WS2, VS1-VS2, US1-US2', 'WS1-WS2, VS1-VS2, US1-US2'), ('S1, S2', 'S1, S2'), ('S1, S2, S3', 'S1, S2, S3')], max_length=50),
        ),
    ]
