# Generated by Django 5.0.14 on 2025-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0011_alter_model_code_tbl_ferrule_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurdenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burden', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FerruleDirectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FerruleNumberMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatioMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='burden',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ferrule_direction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='no_of_ferrules',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ratio',
            field=models.CharField(max_length=50),
        ),
    ]
