# Generated by Django 5.0.14 on 2025-11-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0012_burdenmaster_ferruledirectionmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_code_tbl',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vms_webapp.platform'),
            preserve_default=False,
        ),
    ]
