# Generated by Django 5.0.14 on 2025-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0013_model_code_tbl_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_code_tbl',
            name='model_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
