# Generated by Django 5.0.14 on 2025-11-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0014_model_code_tbl_model_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_code_tbl',
            name='no_of_cables',
        ),
    ]
