# Generated by Django 5.0.14 on 2025-11-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0015_remove_model_code_tbl_no_of_cables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_code_tbl',
            name='part',
        ),
    ]
