# Generated by Django 5.0.14 on 2026-01-16 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0016_remove_model_code_tbl_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_code_tbl',
            name='ferrule_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='model_code_tbl',
            name='no_of_ferrules',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
