# Generated by Django 5.0.14 on 2026-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0017_alter_model_code_tbl_ferrule_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint_tbl',
            name='label_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Label parameters to be verified at QC'),
        ),
    ]
