# Generated by Django 5.0.14 on 2026-01-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0018_checkpoint_tbl_label_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint_tbl',
            name='label_parameters',
        ),
    ]
