# Generated by Django 5.0.14 on 2026-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0019_remove_checkpoint_tbl_label_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_value', models.CharField(max_length=50, unique=True, verbose_name='Class')),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='FSMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs', models.CharField(max_length=50, unique=True, verbose_name='FS')),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FS',
                'verbose_name_plural': 'FS Values',
            },
        ),
        migrations.CreateModel(
            name='KVARatingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kva_rating', models.CharField(max_length=50, unique=True, verbose_name='KVA Rating')),
                ('log_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KVA Rating',
                'verbose_name_plural': 'KVA Ratings',
            },
        ),
        migrations.AddField(
            model_name='part_tbl',
            name='class_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='part_tbl',
            name='fs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FS'),
        ),
        migrations.AddField(
            model_name='part_tbl',
            name='kva_rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KVA Rating'),
        ),
    ]
