# Generated by Django 5.0.14 on 2026-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_webapp', '0020_classmaster_fsmaster_kvaratingmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_tbl',
            name='class_value',
        ),
        migrations.RemoveField(
            model_name='part_tbl',
            name='fs',
        ),
        migrations.RemoveField(
            model_name='part_tbl',
            name='kva_rating',
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='class_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='fs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FS'),
        ),
        migrations.AddField(
            model_name='model_code_tbl',
            name='kva_rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KVA Rating'),
        ),
    ]
